server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway


  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: service-driver
          uri: lb://SERVICE-DRIVER
          predicates:
            - Path=/api/v1/drivers/**
            - Header=Authorization
          filters:
            - name: CircuitBreaker
              args:
                name: serviceDriverCircuitBreaker
                fallbackUri: forward:/fallback/drivers

        - id: service-passenger
          uri: lb://SERVICE-PASSENGER
          predicates:
            - Path=/api/v1/passengers/**
          filters:
            - name: CircuitBreaker
              args:
                name: servicePassengerCircuitBreaker
                fallbackUri: forward:/fallback/passengers

        - id: service-rating
          uri: lb://SERVICE-RATING
          predicates:
            - Path=/api/v1/ratings/**
          filters:
            - name: CircuitBreaker
              args:
                name: serviceRatingCircuitBreaker
                fallbackUri: forward:/fallback/ratings

        - id: service-ride
          uri: lb://SERVICE-RIDE
          predicates:
            - Path=/api/v1/rides/**
          filters:
            - name: CircuitBreaker
              args:
                name: serviceRideCircuitBreaker
                fallbackUri: forward:/fallback/rides

resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true
  circuitbreaker:
    instances:
      serviceDriverCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
      servicePassengerCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
      serviceRatingCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
      serviceRideCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

