server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    application:
      name: api-gateway

    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: service-driver
          uri: lb://SERVICE-DRIVER
          predicates:
            - Path=/api/v1/drivers/**

        - id: service-passenger
          uri: lb://SERVICE-PASSENGER
          predicates:
            - Path=/api/v1/passengers/**

        - id: service-rating
          uri: lb://SERVICE-RATING
          predicates:
            - Path=/api/v1/ratings/**

        - id: service-ride
          uri: lb://SERVICE-RIDE
          predicates:
            - Path=/api/v1/rides/**